/**
 * Everything the app knows, in one place.
 *
 * The care profiles are hand-authored. Watering intervals are a starting
 * point that the weather then moves, and the instruction a plant gives is
 * written so somebody can check it against what is in front of them rather
 * than trusting a number.
 *
 * The plants below are the seeded demo account. Two of them are already due,
 * because a schedule cannot be demonstrated by waiting for it.
 */

export type TaskKind = "water" | "fertilise" | "checkin" | "pest";

export type Species = {
  id: string;
  name: string;
  latin: string;
  waterEvery: number;
  fertiliseEvery: number;
  advice: string;
  /** What to feed it with, and how much. Organic first, every time. */
  feedWith: string;
  /** What actually goes wrong with this plant, and what to do about it. */
  pestWatch: string;
  /** Other names people actually use for it, so a search finds it. */
  aka: string;
  /** Trees, Flowering, Herbs, Vegetables or Indoors. */
  group: string;
  /** Photograph under public/plants, where there is one. */
  photo?: string;
};

export type Plant = {
  id: string;
  name: string;
  speciesId: string;
  place: string;
  plantedOn: string;
  lat: number;
  lon: number;
  streak: number;
  points: number;
  lastWatered: string;
  lastFertilised: string;
};

export const SPECIES: Species[] = [
  {
    id: "neem",
    name: "Neem",
    latin: "Azadirachta indica",
    aka: "nim limbdo",
    group: "Trees",
    waterEvery: 3,
    fertiliseEvery: 45,
    advice: "Water when the soil is dry two inches down.",
    feedWith: "A handful of compost worked into the top inch. Neem asks for very little.",
    pestWatch: "Look under the leaves for scale and mealybug. Wipe them off with soapy water before you reach for anything stronger.",
    photo: "/plants/neem.jpg",
  },
  {
    id: "peepal",
    name: "Peepal",
    latin: "Ficus religiosa",
    aka: "pipal bodhi ashwattha",
    group: "Trees",
    waterEvery: 4,
    fertiliseEvery: 60,
    advice: "Keep it damp while it is young, never waterlogged.",
    feedWith: "Compost twice a year. Young ones take a spoon of vermicompost.",
    pestWatch: "Leaf-eating caterpillars in the monsoon. Pick them off by hand, they are large and few.",
    photo: "/plants/peepal.jpg",
  },
  {
    id: "banyan",
    name: "Banyan",
    latin: "Ficus benghalensis",
    aka: "bargad vat",
    group: "Trees",
    waterEvery: 4,
    fertiliseEvery: 60,
    advice: "Water around the drip line, not against the trunk.",
    feedWith: "Compost at the drip line once a season.",
    pestWatch: "Mostly untroubled. Check aerial roots for borer holes.",
    photo: "/plants/peepal.jpg",
  },
  {
    id: "mango",
    name: "Mango",
    latin: "Mangifera indica",
    aka: "aam",
    group: "Trees",
    waterEvery: 5,
    fertiliseEvery: 40,
    advice: "Deep soak rather than a daily splash.",
    feedWith: "Well-rotted manure at the drip line, never against the trunk.",
    pestWatch: "Hoppers and powdery mildew before flowering. Neem oil spray at dusk, not in the sun.",
    photo: "/plants/mango.jpg",
  },
  {
    id: "jamun",
    name: "Jamun",
    latin: "Syzygium cumini",
    aka: "black plum java plum",
    group: "Trees",
    waterEvery: 4,
    fertiliseEvery: 50,
    advice: "Steady moisture through the first two summers.",
    feedWith: "Manure before the rains, once a year.",
    pestWatch: "Fruit flies and leaf spot. Clear fallen fruit rather than spraying.",
    photo: "/plants/mango.jpg",
  },
  {
    id: "gulmohar",
    name: "Gulmohar",
    latin: "Delonix regia",
    aka: "flame tree royal poinciana",
    group: "Trees",
    waterEvery: 4,
    fertiliseEvery: 50,
    advice: "Let the top of the soil dry between waterings.",
    feedWith: "A light compost dressing before the rains.",
    pestWatch: "Defoliating caterpillars after the first rain. Hand-pick, they pass in a fortnight.",
    photo: "/plants/hibiscus.jpg",
  },
  {
    id: "ashoka",
    name: "Ashoka",
    latin: "Saraca asoca",
    aka: "sita ashok",
    group: "Trees",
    waterEvery: 3,
    fertiliseEvery: 45,
    advice: "Shade-tolerant, but thirsty while it establishes.",
    feedWith: "Compost twice a year while it establishes.",
    pestWatch: "Leaf webber and scale. Prune the affected shoots out.",
    photo: "/plants/sapling.jpg",
  },
  {
    id: "amla",
    name: "Amla",
    latin: "Phyllanthus emblica",
    aka: "indian gooseberry aonla",
    group: "Trees",
    waterEvery: 5,
    fertiliseEvery: 50,
    advice: "Deep water weekly in summer, less once it fruits.",
    feedWith: "Manure at the start of the rains.",
    pestWatch: "Rust and bark-eating caterpillar. Scrape the webbing off the trunk.",
  },
  {
    id: "guava",
    name: "Guava",
    latin: "Psidium guajava",
    aka: "amrood peru",
    group: "Trees",
    waterEvery: 4,
    fertiliseEvery: 35,
    advice: "Even moisture while fruiting, drier after.",
    feedWith: "Compost every month or two through the growing season.",
    pestWatch: "Fruit fly is the main one. Bag the fruit or hang traps.",
  },
  {
    id: "lemon",
    name: "Lemon",
    latin: "Citrus limon",
    aka: "nimbu citrus lime",
    group: "Trees",
    waterEvery: 3,
    fertiliseEvery: 30,
    advice: "Never let it dry out fully, never let it sit wet.",
    feedWith: "Citrus feed or compost plus wood ash, little and often.",
    pestWatch: "Leaf miner and citrus butterfly. Pick the caterpillars off, they are easy to see.",
  },
  {
    id: "pomegranate",
    name: "Pomegranate",
    latin: "Punica granatum",
    aka: "anar",
    group: "Trees",
    waterEvery: 5,
    fertiliseEvery: 40,
    advice: "Let it dry a little between waterings.",
    feedWith: "Manure once before flowering.",
    pestWatch: "Fruit borer. Bag the fruit early.",
  },
  {
    id: "papaya",
    name: "Papaya",
    latin: "Carica papaya",
    aka: "papita",
    group: "Trees",
    waterEvery: 3,
    fertiliseEvery: 30,
    advice: "Frequent light water. It hates standing water at the collar.",
    feedWith: "Compost monthly, it grows fast and eats.",
    pestWatch: "Mealybug and ringspot virus. Remove badly affected plants rather than treating.",
  },
  {
    id: "drumstick",
    name: "Drumstick",
    latin: "Moringa oleifera",
    aka: "moringa sahjan saijan",
    group: "Trees",
    waterEvery: 6,
    fertiliseEvery: 60,
    advice: "Very drought tolerant. Water deeply but rarely.",
    feedWith: "Almost nothing. A little compost once a year.",
    pestWatch: "Hairy caterpillars in the monsoon. Hand-pick.",
  },
  {
    id: "curry-leaf",
    name: "Curry leaf",
    latin: "Murraya koenigii",
    aka: "kadi patta meetha neem",
    group: "Trees",
    waterEvery: 3,
    fertiliseEvery: 35,
    advice: "It likes sun and dislikes sitting in water.",
    feedWith: "Compost plus a spoon of curd water once a month, the old way.",
    pestWatch: "Citrus butterfly caterpillars and psyllids. Pick the caterpillars off, they are easy to see.",
    photo: "/plants/neem.jpg",
  },
  {
    id: "coconut",
    name: "Coconut",
    latin: "Cocos nucifera",
    aka: "nariyal",
    group: "Trees",
    waterEvery: 4,
    fertiliseEvery: 60,
    advice: "Deep water, and salt in the basin once a year.",
    feedWith: "Manure and a handful of salt in the basin annually.",
    pestWatch: "Rhinoceros beetle. Keep the crown clean of rotting matter.",
  },
  {
    id: "banana",
    name: "Banana",
    latin: "Musa acuminata",
    aka: "kela",
    group: "Trees",
    waterEvery: 2,
    fertiliseEvery: 25,
    advice: "Thirsty. Water often, drain well.",
    feedWith: "Heavy feeder: compost every three weeks.",
    pestWatch: "Sigatoka leaf spot. Cut off affected leaves and burn them.",
  },
  {
    id: "arjuna",
    name: "Arjuna",
    latin: "Terminalia arjuna",
    aka: "arjun kahua",
    group: "Trees",
    waterEvery: 5,
    fertiliseEvery: 60,
    advice: "Water weekly until established, then rarely.",
    feedWith: "Compost once a year before the rains.",
    pestWatch: "Largely untroubled once established.",
  },
  {
    id: "bamboo",
    name: "Bamboo",
    latin: "Bambusa vulgaris",
    aka: "baans",
    group: "Trees",
    waterEvery: 3,
    fertiliseEvery: 40,
    advice: "Keep the root zone moist through summer.",
    feedWith: "Compost twice a year.",
    pestWatch: "Bamboo mites on the undersides. Hose them off.",
  },
  {
    id: "tamarind",
    name: "Tamarind",
    latin: "Tamarindus indica",
    aka: "imli",
    group: "Trees",
    waterEvery: 6,
    fertiliseEvery: 60,
    advice: "Deep and infrequent. It handles drought well.",
    feedWith: "Manure once a year.",
    pestWatch: "Mealybug on young shoots.",
  },
  {
    id: "jackfruit",
    name: "Jackfruit",
    latin: "Artocarpus heterophyllus",
    aka: "kathal",
    group: "Trees",
    waterEvery: 4,
    fertiliseEvery: 45,
    advice: "Steady moisture, never waterlogged.",
    feedWith: "Manure twice a year.",
    pestWatch: "Fruit borer and rot. Remove fallen fruit.",
  },
  {
    id: "custard-apple",
    name: "Custard apple",
    latin: "Annona squamosa",
    aka: "sitaphal sharifa",
    group: "Trees",
    waterEvery: 5,
    fertiliseEvery: 45,
    advice: "A dry spell before flowering helps it set.",
    feedWith: "Compost before the rains.",
    pestWatch: "Mealybug in the fruit crevices.",
  },
  {
    id: "chikoo",
    name: "Chikoo",
    latin: "Manilkara zapota",
    aka: "sapota sapodilla",
    group: "Trees",
    waterEvery: 5,
    fertiliseEvery: 45,
    advice: "Even moisture, deep watering.",
    feedWith: "Manure twice a year.",
    pestWatch: "Bud borer. Prune affected tips.",
  },
  {
    id: "bel",
    name: "Bel",
    latin: "Aegle marmelos",
    aka: "bael wood apple",
    group: "Trees",
    waterEvery: 6,
    fertiliseEvery: 55,
    advice: "Very drought hardy once established.",
    feedWith: "Compost once a year.",
    pestWatch: "Largely untroubled.",
  },
  {
    id: "silver-oak",
    name: "Silver oak",
    latin: "Grevillea robusta",
    aka: "silver oak",
    group: "Trees",
    waterEvery: 4,
    fertiliseEvery: 50,
    advice: "Water weekly while young.",
    feedWith: "Light compost once a year. It dislikes rich phosphorus.",
    pestWatch: "Few problems. Watch for scale on young stems.",
  },
  {
    id: "teak",
    name: "Teak",
    latin: "Tectona grandis",
    aka: "sagwan sagon",
    group: "Trees",
    waterEvery: 5,
    fertiliseEvery: 55,
    advice: "Deep water in the first two summers.",
    feedWith: "Compost at the start of the rains.",
    pestWatch: "Teak defoliator in the monsoon. Hand-pick while numbers are small.",
  },
  {
    id: "hibiscus",
    name: "Hibiscus",
    latin: "Hibiscus rosa-sinensis",
    aka: "gudhal jaswand china rose",
    group: "Flowering",
    waterEvery: 2,
    fertiliseEvery: 25,
    advice: "Water daily in summer, half that once it cools.",
    feedWith: "Potash-rich feed while it is flowering.",
    pestWatch: "Aphids on buds, and bud drop from mealybug. Soapy water first, neem oil only if it spreads.",
    photo: "/plants/hibiscus.jpg",
  },
  {
    id: "rose",
    name: "Rose",
    latin: "Rosa indica",
    aka: "gulab",
    group: "Flowering",
    waterEvery: 2,
    fertiliseEvery: 20,
    advice: "Water at the base in the morning, never on the leaves.",
    feedWith: "Compost plus bone meal every three weeks in season.",
    pestWatch: "Black spot, aphids and thrips. Remove affected leaves and improve airflow before spraying.",
  },
  {
    id: "jasmine",
    name: "Jasmine",
    latin: "Jasminum sambac",
    aka: "mogra mallige chameli",
    group: "Flowering",
    waterEvery: 2,
    fertiliseEvery: 25,
    advice: "Keep evenly moist while flowering.",
    feedWith: "Compost monthly through the flowering season.",
    pestWatch: "Budworm and aphids. Pinch off affected buds.",
  },
  {
    id: "marigold",
    name: "Marigold",
    latin: "Tagetes erecta",
    aka: "genda",
    group: "Flowering",
    waterEvery: 2,
    fertiliseEvery: 20,
    advice: "Water at the base, keep the flowers dry.",
    feedWith: "Compost every three weeks.",
    pestWatch: "Red spider mite in dry heat. Spray the undersides with water.",
  },
  {
    id: "bougainvillea",
    name: "Bougainvillea",
    latin: "Bougainvillea glabra",
    aka: "kagaz phool boganvilla",
    group: "Flowering",
    waterEvery: 6,
    fertiliseEvery: 45,
    advice: "Keep it thirsty. It flowers when it is slightly stressed.",
    feedWith: "Very little. Too much feed gives leaves and no colour.",
    pestWatch: "Mealybug and caterpillars. Prune hard after flowering.",
  },
  {
    id: "plumeria",
    name: "Plumeria",
    latin: "Plumeria rubra",
    aka: "champa frangipani",
    group: "Flowering",
    waterEvery: 6,
    fertiliseEvery: 45,
    advice: "Let it dry between waterings, almost none in winter.",
    feedWith: "Compost twice in the growing season.",
    pestWatch: "Plumeria rust, orange dust on the leaf undersides. Remove affected leaves.",
  },
  {
    id: "oleander",
    name: "Oleander",
    latin: "Nerium oleander",
    aka: "kaner",
    group: "Flowering",
    waterEvery: 4,
    fertiliseEvery: 40,
    advice: "Drought tolerant once established.",
    feedWith: "Compost twice a year.",
    pestWatch: "Oleander caterpillar. Hand-pick, and wear gloves, the sap irritates.",
  },
  {
    id: "ixora",
    name: "Ixora",
    latin: "Ixora coccinea",
    aka: "rugmini chethi",
    group: "Flowering",
    waterEvery: 3,
    fertiliseEvery: 30,
    advice: "Even moisture and slightly acid soil.",
    feedWith: "Compost monthly, it likes a slightly acid feed.",
    pestWatch: "Scale and sooty mould. Wipe the leaves.",
  },
  {
    id: "periwinkle",
    name: "Periwinkle",
    latin: "Catharanthus roseus",
    aka: "sadabahar sadaphuli",
    group: "Flowering",
    waterEvery: 3,
    fertiliseEvery: 30,
    advice: "Let the top dry out. It hates wet feet.",
    feedWith: "Very little. It flowers on poor soil.",
    pestWatch: "Root rot from overwatering is the real risk.",
  },
  {
    id: "chandni",
    name: "Chandni",
    latin: "Tabernaemontana divaricata",
    aka: "crape jasmine tagar",
    group: "Flowering",
    waterEvery: 3,
    fertiliseEvery: 30,
    advice: "Steady moisture in summer.",
    feedWith: "Compost every two months.",
    pestWatch: "Mealybug in the leaf joints.",
  },
  {
    id: "tecoma",
    name: "Tecoma",
    latin: "Tecoma stans",
    aka: "yellow bells",
    group: "Flowering",
    waterEvery: 4,
    fertiliseEvery: 40,
    advice: "Dry between waterings.",
    feedWith: "Light compost twice a year.",
    pestWatch: "Few problems.",
  },
  {
    id: "chrysanthemum",
    name: "Chrysanthemum",
    latin: "Chrysanthemum indicum",
    aka: "guldaudi sevanti",
    group: "Flowering",
    waterEvery: 2,
    fertiliseEvery: 20,
    advice: "Keep moist while it is budding.",
    feedWith: "Compost every two weeks in bud.",
    pestWatch: "Aphids and leaf miner.",
  },
  {
    id: "crossandra",
    name: "Crossandra",
    latin: "Crossandra infundibuliformis",
    aka: "abli kanakambaram",
    group: "Flowering",
    waterEvery: 2,
    fertiliseEvery: 25,
    advice: "Evenly moist, warm and bright.",
    feedWith: "Compost monthly.",
    pestWatch: "Nematodes in old soil. Repot rather than treat.",
  },
  {
    id: "tulsi",
    name: "Tulsi",
    latin: "Ocimum tenuiflorum",
    aka: "holy basil vrinda",
    group: "Herbs",
    waterEvery: 2,
    fertiliseEvery: 30,
    advice: "Morning water, and pinch the flower spikes off.",
    feedWith: "A pinch of vermicompost every few weeks. It wants little and often.",
    pestWatch: "Aphids and whitefly on the new growth. A spray of water with a little soap clears them.",
    photo: "/plants/tulsi.jpg",
  },
  {
    id: "basil",
    name: "Basil",
    latin: "Ocimum basilicum",
    aka: "sweet basil sabja",
    group: "Herbs",
    waterEvery: 2,
    fertiliseEvery: 25,
    advice: "Water in the morning, keep the leaves dry.",
    feedWith: "Light compost every three weeks.",
    pestWatch: "Aphids and whitefly. Soapy water.",
  },
  {
    id: "mint",
    name: "Mint",
    latin: "Mentha spicata",
    aka: "pudina",
    group: "Herbs",
    waterEvery: 2,
    fertiliseEvery: 25,
    advice: "Likes it damp. Keep it in its own pot or it takes over.",
    feedWith: "Compost monthly.",
    pestWatch: "Rust, orange spots underneath. Cut it back hard.",
  },
  {
    id: "coriander",
    name: "Coriander",
    latin: "Coriandrum sativum",
    aka: "dhania cilantro",
    group: "Herbs",
    waterEvery: 2,
    fertiliseEvery: 25,
    advice: "Steady moisture, and shade in peak summer.",
    feedWith: "Light compost every three weeks.",
    pestWatch: "Aphids. Rinse them off.",
  },
  {
    id: "lemongrass",
    name: "Lemongrass",
    latin: "Cymbopogon citratus",
    aka: "nimbu ghas",
    group: "Herbs",
    waterEvery: 3,
    fertiliseEvery: 35,
    advice: "Water well in summer, less in winter.",
    feedWith: "Compost twice a year.",
    pestWatch: "Rust in humid weather. Thin the clump.",
  },
  {
    id: "ajwain-plant",
    name: "Ajwain plant",
    latin: "Plectranthus amboinicus",
    aka: "owa cuban oregano pathar chur",
    group: "Herbs",
    waterEvery: 4,
    fertiliseEvery: 35,
    advice: "Let it dry between waterings, it stores water.",
    feedWith: "Very little compost.",
    pestWatch: "Mealybug. Wipe off with cotton.",
  },
  {
    id: "chilli",
    name: "Chilli",
    latin: "Capsicum annuum",
    aka: "mirchi pepper",
    group: "Herbs",
    waterEvery: 2,
    fertiliseEvery: 25,
    advice: "Even moisture while fruiting.",
    feedWith: "Compost every three weeks.",
    pestWatch: "Thrips and leaf curl. Remove curled leaves early.",
  },
  {
    id: "ginger",
    name: "Ginger",
    latin: "Zingiber officinale",
    aka: "adrak",
    group: "Herbs",
    waterEvery: 3,
    fertiliseEvery: 35,
    advice: "Moist and shaded, never waterlogged.",
    feedWith: "Compost monthly in the growing season.",
    pestWatch: "Rhizome rot in wet soil. Improve the drainage.",
  },
  {
    id: "turmeric",
    name: "Turmeric",
    latin: "Curcuma longa",
    aka: "haldi",
    group: "Herbs",
    waterEvery: 3,
    fertiliseEvery: 35,
    advice: "Keep damp through the growing season.",
    feedWith: "Compost monthly.",
    pestWatch: "Leaf spot. Remove affected leaves.",
  },
  {
    id: "aloe",
    name: "Aloe vera",
    latin: "Aloe barbadensis",
    aka: "gwarpatha ghritkumari",
    group: "Herbs",
    waterEvery: 10,
    fertiliseEvery: 90,
    advice: "Far less water than feels right. Let it dry out.",
    feedWith: "Almost nothing. A little compost once a year.",
    pestWatch: "Root rot from overwatering is the real risk, not pests.",
    photo: "/plants/aloe.jpg",
  },
  {
    id: "stevia",
    name: "Stevia",
    latin: "Stevia rebaudiana",
    aka: "meethi tulsi",
    group: "Herbs",
    waterEvery: 2,
    fertiliseEvery: 30,
    advice: "Keep lightly moist, it has shallow roots.",
    feedWith: "Light compost monthly.",
    pestWatch: "Few problems. Pinch the tips to keep it bushy.",
  },
  {
    id: "tomato",
    name: "Tomato",
    latin: "Solanum lycopersicum",
    aka: "tamatar",
    group: "Vegetables",
    waterEvery: 2,
    fertiliseEvery: 20,
    advice: "Water at the base, evenly. Uneven water splits the fruit.",
    feedWith: "Compost every two weeks once it sets fruit.",
    pestWatch: "Fruit borer and early blight. Remove the lower leaves that touch the soil.",
  },
  {
    id: "brinjal",
    name: "Brinjal",
    latin: "Solanum melongena",
    aka: "baingan eggplant aubergine",
    group: "Vegetables",
    waterEvery: 2,
    fertiliseEvery: 25,
    advice: "Steady moisture while fruiting.",
    feedWith: "Compost every three weeks.",
    pestWatch: "Shoot and fruit borer. Cut off wilting shoots.",
  },
  {
    id: "okra",
    name: "Okra",
    latin: "Abelmoschus esculentus",
    aka: "bhindi ladies finger",
    group: "Vegetables",
    waterEvery: 2,
    fertiliseEvery: 25,
    advice: "Water deeply twice a week in summer.",
    feedWith: "Compost every three weeks.",
    pestWatch: "Yellow vein mosaic, carried by whitefly. Remove infected plants.",
  },
  {
    id: "spinach",
    name: "Spinach",
    latin: "Spinacia oleracea",
    aka: "palak",
    group: "Vegetables",
    waterEvery: 2,
    fertiliseEvery: 20,
    advice: "Keep the soil damp, it bolts if it dries.",
    feedWith: "Light compost every two weeks.",
    pestWatch: "Leaf miner. Pick the tunnelled leaves off.",
  },
  {
    id: "bottle-gourd",
    name: "Bottle gourd",
    latin: "Lagenaria siceraria",
    aka: "lauki dudhi",
    group: "Vegetables",
    waterEvery: 2,
    fertiliseEvery: 25,
    advice: "Water at the base, deeply.",
    feedWith: "Compost every three weeks.",
    pestWatch: "Fruit fly. Bag the young fruit.",
  },
  {
    id: "bitter-gourd",
    name: "Bitter gourd",
    latin: "Momordica charantia",
    aka: "karela",
    group: "Vegetables",
    waterEvery: 2,
    fertiliseEvery: 25,
    advice: "Even moisture on a trellis.",
    feedWith: "Compost every three weeks.",
    pestWatch: "Fruit fly. Traps work better than spray.",
  },
  {
    id: "cucumber",
    name: "Cucumber",
    latin: "Cucumis sativus",
    aka: "kheera",
    group: "Vegetables",
    waterEvery: 2,
    fertiliseEvery: 20,
    advice: "Consistent water, or the fruit turns bitter.",
    feedWith: "Compost every two weeks.",
    pestWatch: "Powdery mildew. Improve airflow, water in the morning.",
  },
  {
    id: "beans",
    name: "Beans",
    latin: "Phaseolus vulgaris",
    aka: "sem french beans",
    group: "Vegetables",
    waterEvery: 2,
    fertiliseEvery: 25,
    advice: "Water at the base, keep the foliage dry.",
    feedWith: "Little feed. Beans make their own nitrogen.",
    pestWatch: "Pod borer. Pick affected pods.",
  },
  {
    id: "money-plant",
    name: "Money plant",
    latin: "Epipremnum aureum",
    aka: "pothos devils ivy",
    group: "Indoors",
    waterEvery: 6,
    fertiliseEvery: 40,
    advice: "Wait until the top inch is properly dry.",
    feedWith: "Quarter-strength liquid feed, and skip it in winter.",
    pestWatch: "Mealybug in the leaf joints. Dab with cotton and diluted alcohol.",
    photo: "/plants/money-plant.jpg",
  },
  {
    id: "snake-plant",
    name: "Snake plant",
    latin: "Sansevieria trifasciata",
    aka: "sansevieria nag phani",
    group: "Indoors",
    waterEvery: 14,
    fertiliseEvery: 90,
    advice: "Almost never. Once a fortnight is plenty.",
    feedWith: "A little compost once a year.",
    pestWatch: "Root rot from overwatering. Nothing else bothers it.",
  },
  {
    id: "jade",
    name: "Jade plant",
    latin: "Crassula ovata",
    aka: "crassula money tree",
    group: "Indoors",
    waterEvery: 10,
    fertiliseEvery: 60,
    advice: "Let it dry right out between waterings.",
    feedWith: "Very little, twice a year.",
    pestWatch: "Mealybug. Cotton and alcohol.",
  },
  {
    id: "spider-plant",
    name: "Spider plant",
    latin: "Chlorophytum comosum",
    aka: "airplane plant",
    group: "Indoors",
    waterEvery: 5,
    fertiliseEvery: 40,
    advice: "Keep lightly moist, it browns at the tips if starved.",
    feedWith: "Light feed monthly in summer.",
    pestWatch: "Brown tips are usually the water, not a pest.",
  },
  {
    id: "peace-lily",
    name: "Peace lily",
    latin: "Spathiphyllum wallisii",
    aka: "spathiphyllum",
    group: "Indoors",
    waterEvery: 4,
    fertiliseEvery: 40,
    advice: "It droops when thirsty and recovers fast. Try not to make that the routine.",
    feedWith: "Light feed every six weeks.",
    pestWatch: "Scale on the undersides. Wipe them off.",
  },
  {
    id: "areca-palm",
    name: "Areca palm",
    latin: "Dypsis lutescens",
    aka: "butterfly palm",
    group: "Indoors",
    waterEvery: 4,
    fertiliseEvery: 45,
    advice: "Keep the root ball damp, never soggy.",
    feedWith: "Compost twice a year.",
    pestWatch: "Spider mite in dry air. Mist and hose the leaves.",
  },
  {
    id: "rubber-plant",
    name: "Rubber plant",
    latin: "Ficus elastica",
    aka: "rubber fig",
    group: "Indoors",
    waterEvery: 7,
    fertiliseEvery: 45,
    advice: "Let the top two inches dry first.",
    feedWith: "Feed monthly in summer only.",
    pestWatch: "Scale. Wipe the leaves with soapy water.",
  },
  {
    id: "monstera",
    name: "Monstera",
    latin: "Monstera deliciosa",
    aka: "swiss cheese plant",
    group: "Indoors",
    waterEvery: 7,
    fertiliseEvery: 40,
    advice: "Water when the top two inches are dry.",
    feedWith: "Monthly feed in the growing season.",
    pestWatch: "Spider mite in dry air. Raise the humidity.",
  },
  {
    id: "zz-plant",
    name: "ZZ plant",
    latin: "Zamioculcas zamiifolia",
    aka: "zanzibar gem",
    group: "Indoors",
    waterEvery: 14,
    fertiliseEvery: 90,
    advice: "Forget about it. That is the care instruction.",
    feedWith: "Twice a year at most.",
    pestWatch: "Almost nothing. Rot is the only real risk.",
  },
  {
    id: "syngonium",
    name: "Syngonium",
    latin: "Syngonium podophyllum",
    aka: "arrowhead plant",
    group: "Indoors",
    waterEvery: 5,
    fertiliseEvery: 40,
    advice: "Keep lightly moist.",
    feedWith: "Light feed monthly.",
    pestWatch: "Mealybug. Cotton and alcohol.",
  },
  {
    id: "fern",
    name: "Fern",
    latin: "Nephrolepis exaltata",
    aka: "boston fern",
    group: "Indoors",
    waterEvery: 3,
    fertiliseEvery: 40,
    advice: "Never let it dry out, and keep the air humid.",
    feedWith: "Light feed every six weeks.",
    pestWatch: "Brown fronds are usually dry air.",
  },
  {
    id: "anthurium",
    name: "Anthurium",
    latin: "Anthurium andraeanum",
    aka: "flamingo flower",
    group: "Indoors",
    waterEvery: 5,
    fertiliseEvery: 40,
    advice: "Moist but airy. It hates dense wet soil.",
    feedWith: "Light feed monthly in summer.",
    pestWatch: "Scale and mealybug. Wipe them off.",
  },
  {
    id: "croton",
    name: "Croton",
    latin: "Codiaeum variegatum",
    aka: "garden croton",
    group: "Indoors",
    waterEvery: 4,
    fertiliseEvery: 35,
    advice: "Even moisture and strong light for the colour.",
    feedWith: "Compost every two months.",
    pestWatch: "Spider mite. Hose the undersides.",
  },
  {
    id: "coleus",
    name: "Coleus",
    latin: "Plectranthus scutellarioides",
    aka: "painted nettle",
    group: "Indoors",
    waterEvery: 2,
    fertiliseEvery: 30,
    advice: "Keep damp, and pinch the flower spikes off.",
    feedWith: "Light feed every three weeks.",
    pestWatch: "Mealybug and whitefly.",
  },
  {
    id: "cactus",
    name: "Cactus",
    latin: "Echinopsis oxygona",
    aka: "cacti",
    group: "Indoors",
    waterEvery: 21,
    fertiliseEvery: 120,
    advice: "Water deeply, then leave it for weeks.",
    feedWith: "Almost never.",
    pestWatch: "Mealybug in the crevices. Rot from kindness.",
  },
  {
    id: "lucky-bamboo",
    name: "Lucky bamboo",
    latin: "Dracaena sanderiana",
    aka: "dracaena",
    group: "Indoors",
    waterEvery: 7,
    fertiliseEvery: 60,
    advice: "In water, change it fortnightly. In soil, keep it lightly damp.",
    feedWith: "A drop of feed every couple of months.",
    pestWatch: "Yellowing is usually the water, not a pest.",
  },
  {
    id: "other-tree",
    name: "Any other tree",
    latin: "",
    aka: "tree sapling unknown other",
    group: "Anything else",
    waterEvery: 4,
    fertiliseEvery: 50,
    advice: "Deep water at the drip line rather than a daily splash. Less often as it establishes.",
    feedWith: "Compost or well-rotted manure at the drip line, once or twice a year.",
    pestWatch: "Look under the leaves and along the trunk. Most tree trouble shows there first.",
  },
  {
    id: "other-flowering",
    name: "Any other flowering plant",
    latin: "",
    aka: "flower shrub unknown other",
    group: "Anything else",
    waterEvery: 2,
    fertiliseEvery: 25,
    advice: "Water at the base in the morning. Keep the flowers and leaves dry.",
    feedWith: "Compost every three weeks while it is flowering, less once it stops.",
    pestWatch: "Aphids and mites on the buds and new growth. Soapy water before anything stronger.",
  },
  {
    id: "other-herb",
    name: "Any other herb or vegetable",
    latin: "",
    aka: "herb vegetable edible unknown other",
    group: "Anything else",
    waterEvery: 2,
    fertiliseEvery: 25,
    advice: "Keep it evenly damp. Most of these bolt or drop fruit if they dry out and then flood.",
    feedWith: "Light compost every two or three weeks through the growing season.",
    pestWatch: "Check the undersides weekly. Anything you eat is better hand-picked than sprayed.",
  },
  {
    id: "other-succulent",
    name: "Any other succulent or cactus",
    latin: "",
    aka: "succulent cactus aloe unknown other",
    group: "Anything else",
    waterEvery: 14,
    fertiliseEvery: 90,
    advice: "Far less than feels right. Let it dry right through, then water deeply.",
    feedWith: "Almost nothing. A little compost once a year.",
    pestWatch: "Rot from kindness is the real risk. Mealybug in the crevices otherwise.",
  },
  {
    id: "other-indoor",
    name: "Any other houseplant",
    latin: "",
    aka: "indoor houseplant pot unknown other",
    group: "Anything else",
    waterEvery: 6,
    fertiliseEvery: 40,
    advice: "Wait until the top inch is properly dry, then water until it runs through.",
    feedWith: "Quarter-strength liquid feed monthly in summer, none in winter.",
    pestWatch: "Mealybug in the leaf joints and scale on the undersides. Wipe them off.",
  },
];

export const PLANTS: Plant[] = [
  {
    id: "neem-1",
    name: "Neem",
    speciesId: "neem",
    place: "backyard",
    plantedOn: "2026-06-14",
    lat: 26.9124,
    lon: 75.7873,
    streak: 12,
    points: 820,
    lastWatered: "-5",
    lastFertilised: "-20",
  },
  {
    id: "tulsi-1",
    name: "Tulsi",
    speciesId: "tulsi",
    place: "balcony",
    plantedOn: "2026-08-02",
    lat: 26.9126,
    lon: 75.787,
    streak: 6,
    points: 310,
    lastWatered: "-2",
    lastFertilised: "-12",
  },
  {
    id: "money-1",
    name: "Money plant",
    speciesId: "money-plant",
    place: "living room",
    plantedOn: "2026-05-20",
    lat: 26.9125,
    lon: 75.7871,
    streak: 21,
    points: 1010,
    lastWatered: "-3",
    lastFertilised: "-38",
  },
];

export function species(id: string): Species {
  const found = SPECIES.find((s) => s.id === id);
  if (!found) throw new Error("unknown species: " + id);
  return found;
}

export function plant(id: string): Plant | undefined {
  return PLANTS.find((p) => p.id === id);
}

export const POINTS: Record<TaskKind, number> = {
  water: 30,
  fertilise: 50,
  checkin: 15,
  pest: 35,
};

export const TASK_LABEL: Record<TaskKind, string> = {
  water: "Water it",
  fertilise: "Feed it",
  checkin: "Check the leaves",
  pest: "Check for pests",
};

/**
 * What the proof photo has to show. This is shown to the user before the
 * camera opens, and it is the same thing the verifier checks. A user who
 * follows the instruction passes every time.
 */
export const TASK_INSTRUCTION: Record<TaskKind, string> = {
  water:
    "Photograph the plant while you pour. Keep the base of the plant and the wet soil both in frame.",
  fertilise:
    "Photograph the base of the plant with the feed spread on the soil, before you water it in.",
  checkin:
    "Photograph the whole plant, close enough that the leaves are clear.",
  pest:
    "Photograph the underside of a few leaves and the new growth, close. That is where trouble starts and where it is visible first.",
};

/** The streak multiplier. Consistency is worth more than a single burst. */
export function multiplier(streak: number): number {
  if (streak >= 30) return 2;
  if (streak >= 14) return 1.4;
  if (streak >= 7) return 1.2;
  return 1;
}

export function pointsFor(kind: TaskKind, streak: number): number {
  return Math.round(POINTS[kind] * multiplier(streak));
}

export const TOTAL_POINTS = 2140;
